name: charge_sound
description: Change the charge sound played on laptop
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  dart_ipc: ^1.0.1
  ffi: ^2.1.3
  hive: ^2.2.3
  json_rpc_2: ^3.0.3
  logger: ^2.4.0
  win32: ^5.5.4
  yaml: ^3.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
