name: power_chime
description: Change the charge sound played on laptop
version: 1.1.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  logger: ^2.4.0
  win32: ^5.5.4
  yaml: ^3.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
