name: Build

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*.*.*'  # Triggers the workflow on version tags like v1.0.0, v2.1.3, etc.
    # inputs:
    #   version:
    #     type: string
    #     description: "Set the version number of this build"
    #     required: true
      
    #   distro:
    #     type: choice
    #     default: Release
    #     description: Set the distro channel of this build
    #     required: true
    #     options: 
    #     - Alpha
    #     - Beta
    #     - Release

jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Install Checkout@v3
        uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1

      - name: Get dependence
        run: dart pub get

      - name: Parse Version
        id: parse_version
        shell: pwsh
        run: |
          $match = Select-String -Path pubspec.yaml 'version: \d+.\d+..+' -AllMatches
          $version = $match.Matches.Value.replace("version: ", "")
          "VERSION=$version" >> $env:GITHUB_ENV
          Write-Host "Version parsed successfully ($version)"
          
          echo "::set-output name=version::$version"
      
      - name: Build App
        run: dart compile exe bin/main.dart -o charge-sound.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: "v${{ steps.parse_version.outputs.version }}"
          name: "v${{ steps.parse_version.outputs.version }}"
          files: "charge-sound.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}